#ifndef CAPTURE_PROFILE_H
#define CAPTURE_PROFILE_H

// Capture target IDs. The default build is still MV1C/MVS.
#define NEOPICO_CAPTURE_TARGET_MVS 0
#define NEOPICO_CAPTURE_TARGET_SNES 1

#ifndef NEOPICO_CAPTURE_TARGET
#define NEOPICO_CAPTURE_TARGET NEOPICO_CAPTURE_TARGET_MVS
#endif

#if NEOPICO_CAPTURE_TARGET == NEOPICO_CAPTURE_TARGET_MVS

#define CAPTURE_TARGET_NAME "MVS"
#define CAPTURE_FRAME_WIDTH 320
#define CAPTURE_FRAME_HEIGHT 240
#define CAPTURE_ACTIVE_WIDTH 320
#define CAPTURE_ACTIVE_HEIGHT 224
#define CAPTURE_ACTIVE_X_OFFSET 0

// Neo Geo MV1C: 8 MHz / 144 = 55,555.555... Hz.
#define CAPTURE_AUDIO_INPUT_RATE 55556
#define CAPTURE_AUDIO_RATE_MIN 53000
#define CAPTURE_AUDIO_RATE_MAX 58000
#define CAPTURE_AUDIO_INACTIVITY_RESTART_DEFAULT 1

#elif NEOPICO_CAPTURE_TARGET == NEOPICO_CAPTURE_TARGET_SNES

#define CAPTURE_TARGET_NAME "SNES"
#define CAPTURE_FRAME_WIDTH 320
#define CAPTURE_FRAME_HEIGHT 240
#define CAPTURE_ACTIVE_WIDTH 256
#define CAPTURE_ACTIVE_HEIGHT 224
#define CAPTURE_ACTIVE_X_OFFSET ((CAPTURE_FRAME_WIDTH - CAPTURE_ACTIVE_WIDTH) / 2)

// SNES S-DSP nominal rate from DCK/256, about 32.04 kHz.
#define CAPTURE_AUDIO_INPUT_RATE 32040
#define CAPTURE_AUDIO_RATE_MIN 30000
#define CAPTURE_AUDIO_RATE_MAX 34000
// The SNES digital audio stream can pause during silence/no-audio, so do not
// treat sustained DMA inactivity as a capture fault by default.
#define CAPTURE_AUDIO_INACTIVITY_RESTART_DEFAULT 0

#else
#error "Unsupported NEOPICO_CAPTURE_TARGET"
#endif

#endif // CAPTURE_PROFILE_H
